brew automake
brew fd
brew gcc
brew htop
brew iperf3
brew lua
brew macvim
brew make
brew neofetch
brew neovim
brew ninja
brew node
brew openssl@1.1
brew openssl@3
brew p11-kit
brew pandoc
brew poppler
brew portaudio
brew powerlevel10k
brew protobuf
brew pyenv
brew pygments
brew python-packaging
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.13
brew python@3.9
brew qmk
brew ruby
brew screenresolution
brew skhd
brew sqlite
brew starship
brew stow
brew synctex
brew tree-sitter
brew unbound
brew unzip
brew uv
brew zathura
brew zathura-pdf-poppler

# casks
cask alfred
cask alt-tab
cask apparency
cask battery-toolkit
cask ghostty
cask git-credential-manager
cask iterm2
cask launchcontrol
cask maccy
cask monitorcontrol
cask qlcolorcode
cask qlstephen
cask quicklook-json

# app store
mas 'MoneyMoney', id: 872698314
mas 'Microsoft Word', id: 462054704
mas 'Microsoft Excel', id: 462058435

